location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
    - image: {{ .Image }}
      name: backend
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: ConnectionStrings__AzureBlobs
        value: {{ .Env.SERVICE_BINDING_AZUREBLOBS_ENDPOINT }}
      - name: ConnectionStrings__AzureQueues
        value: {{ .Env.SERVICE_BINDING_AZUREQUEUES_ENDPOINT }}
      - name: ConnectionStrings__pubsub
        value: {{ connectionString "pubsub" }}
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
      - name: QDRANT_ENDPOINT
        value: http://qdrant.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
      - name: services__historyservice__0
        value: http://historyservice.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
      - name: services__historyservice__1
        value: https://historyservice.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
      - name: AZURE_OPENAI_GPT_NAME
        value: {{ .Env.AZURE_OPENAI_GPT_NAME }}
      - name: AZURE_OPENAI_TEXT_EMBEDDING_NAME
        value: {{ .Env.AZURE_OPENAI_TEXT_EMBEDDING_NAME }}
      - name: AZURE_OPENAI_ENDPOINT
        value: {{ .Env.AZURE_OPENAI_ENDPOINT }}
      - name: AZURE_OPENAI_KEY_NAME
        value: {{ .Env.AZURE_OPENAI_KEY_NAME }}
      - name: AZURE_KEY_VAULT_ENDPOINT
        value: {{ .Env.AZURE_KEY_VAULT_ENDPOINT }}
    scale:
      minReplicas: 1
      maxReplicas: 1
tags:
  azd-service-name: backend
  aspire-resource-name: backend
